import { Book, Category } from "./books-store";

export const DEFAULT_CATEGORIES: Category[] = [
  { id: "cat-1", name: "Banking Exams", seoslug: "banking-exams" },
  { id: "cat-2", name: "UPSC", seoslug: "upsc" },
  { id: "cat-3", name: "SSC", seoslug: "ssc" },
  { id: "cat-4", name: "State PSC", seoslug: "state-psc" },
  { id: "cat-5", name: "Railways", seoslug: "railways" },
  { id: "cat-6", name: "Defense", seoslug: "defense" },
  { id: "cat-7", name: "Insurance", seoslug: "insurance" },
  { id: "cat-8", name: "Teaching", seoslug: "teaching" },
  { id: "cat-9", name: "Engineering", seoslug: "engineering" },
  { id: "cat-10", name: "Medical", seoslug: "medical" },
  { id: "cat-11", name: "Law", seoslug: "law" },
  { id: "cat-12", name: "Management", seoslug: "management" },
];

export const DEFAULT_BOOKS: Book[] = [
  {
    id: "book-1",
    title: "IBPS Clerk Paper & Solutions",
    seoslug: "ibps-clerk-paper",
    category: "Banking Exams",
    publsher: "Exam Kart Press",
    pdfurl: "https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf",
    sampleurl: "https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf",
    listprice: "199",
    buyprice: "99",
    seoDescription: "Complete solved papers and mock tests for IBPS Clerk exam preparation.",
    fullDescription: "Comprehensive guide featuring 10+ previous year papers, detailed step-by-step solutions, quantitative aptitude shortcuts, and reasoning mock papers tailored for IBPS Clerk aspirants.",
    tags: ["banking", "clerk", "solved papers", "ibps"],
    averageRating: 4.6,
    reviewCount: 142,
    language: "English",
    pageCount: 180,
    fileSizeInMB: 14.2,
  },
  {
    id: "book-2",
    title: "SBI PO Mains 2024 Masterclass",
    seoslug: "sbi-po-mains-2024",
    category: "Banking Exams",
    publsher: "Exam Kart Press",
    pdfurl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    sampleurl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    listprice: "249",
    buyprice: "149",
    seoDescription: "Advanced SBI PO Mains study guide with data interpretation and English essay strategies.",
    fullDescription: "Master SBI PO Mains with high-level DI sets, analytical reasoning, banking awareness summaries, and descriptive paper writing templates. Includes 5 full-length mock tests with answer keys.",
    tags: ["sbi po", "mains", "banking", "data interpretation"],
    averageRating: 4.8,
    reviewCount: 380,
    language: "English",
    pageCount: 220,
    fileSizeInMB: 18.5,
  },
  {
    id: "book-3",
    title: "UPSC Prelims CSAT Complete Guide",
    seoslug: "upsc-prelims-csat",
    category: "UPSC",
    publsher: "Civil Services Horizon",
    pdfurl: "https://www.orimi.com/pdf-test.pdf",
    sampleurl: "https://www.orimi.com/pdf-test.pdf",
    listprice: "299",
    buyprice: "199",
    seoDescription: "UPSC Prelims Paper II CSAT preparation book covering math, comprehension, and decision making.",
    fullDescription: "Thorough coverage of Paper II CSAT topics: reading comprehension passages, logical reasoning, numerical ability, and data sufficiency. Includes 12 years of UPSC Prelims solved questions.",
    tags: ["upsc", "csat", "prelims", "civil services"],
    averageRating: 4.7,
    reviewCount: 520,
    language: "English",
    pageCount: 260,
    fileSizeInMB: 22.0,
  },
  {
    id: "book-4",
    title: "SSC CGL Tier 1 All-in-One Guide",
    seoslug: "ssc-cgl-tier-1",
    category: "SSC",
    publsher: "Staff Selection Experts",
    pdfurl: "https://pdfobject.com/pdf/sample.pdf",
    sampleurl: "https://pdfobject.com/pdf/sample.pdf",
    listprice: "149",
    buyprice: "89",
    seoDescription: "Top rated preparation material for SSC CGL Tier 1 general awareness, math and English.",
    fullDescription: "Shortcut tricks for Quantitative Aptitude, static GK tables, current affairs highlights, and 15 practice sets designed strictly according to the latest SSC CGL exam pattern.",
    tags: ["ssc", "cgl", "tier 1", "general knowledge"],
    averageRating: 4.4,
    reviewCount: 215,
    language: "English",
    pageCount: 160,
    fileSizeInMB: 12.8,
  },
  {
    id: "book-5",
    title: "RRB NTPC CBT 1 & 2 Strategy Guide",
    seoslug: "rrb-ntpc-guide",
    category: "Railways",
    publsher: "Railway Prep Depot",
    pdfurl: "https://www.clickdimensions.com/links/TestPDFfile.pdf",
    sampleurl: "https://www.clickdimensions.com/links/TestPDFfile.pdf",
    listprice: "199",
    buyprice: "129",
    seoDescription: "Complete book for Railway Recruitment Board Non-Technical Popular Categories examination.",
    fullDescription: "Comprehensive topic-wise guide covering General Science, Mathematics, General Intelligence, and Reasoning. Features 2500+ objective practice questions with detailed explanations.",
    tags: ["rrb", "ntpc", "railways", "science"],
    averageRating: 4.3,
    reviewCount: 168,
    language: "English",
    pageCount: 195,
    fileSizeInMB: 15.1,
  },
  {
    id: "book-6",
    title: "NDA & NA Mathematics Formula & Practice",
    seoslug: "nda-mathematics",
    category: "Defense",
    publsher: "Defense Wings",
    pdfurl: "https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/554832/Sample_PDF_Document.pdf",
    sampleurl: "https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/554832/Sample_PDF_Document.pdf",
    listprice: "249",
    buyprice: "179",
    seoDescription: "Mathematics guide for NDA entrance exam with algebra, calculus and trigonometry formulas.",
    fullDescription: "Targeted math module for National Defence Academy aspirants. Includes quick formula sheets, calculus shortcuts, 3D geometry visuals, and 8 years of UPSC NDA past paper solutions.",
    tags: ["nda", "defense", "math", "calculus"],
    averageRating: 4.8,
    reviewCount: 295,
    language: "English",
    pageCount: 210,
    fileSizeInMB: 17.3,
  },
  {
    id: "book-7",
    title: "LIC AAO Financial & Insurance Awareness",
    seoslug: "lic-aao-mock",
    category: "Insurance",
    publsher: "Exam Kart Press",
    pdfurl: "https://unec.edu.az/application/uploads/2014/12/pdf-sample.pdf",
    sampleurl: "https://unec.edu.az/application/uploads/2014/12/pdf-sample.pdf",
    listprice: "129",
    buyprice: "79",
    seoDescription: "Specialized insurance market awareness and financial notes for LIC Assistant Administrative Officer.",
    fullDescription: "Essential insurance terminology, financial sector updates, IRDAI regulations summary, and 10 full mock test papers for LIC AAO Prelims and Mains examinations.",
    tags: ["lic", "insurance", "aao", "finance"],
    averageRating: 4.5,
    reviewCount: 98,
    language: "English",
    pageCount: 140,
    fileSizeInMB: 10.9,
  },
  {
    id: "book-8",
    title: "CTET Paper 1 & 2 Pedagogy & Practice",
    seoslug: "ctet-paper-1-2",
    category: "Teaching",
    publsher: "EduTeachers Publication",
    pdfurl: "https://morth.nic.in/sites/default/files/SOP-for-Drivers-Training-Centres.pdf",
    sampleurl: "https://morth.nic.in/sites/default/files/SOP-for-Drivers-Training-Centres.pdf",
    listprice: "249",
    buyprice: "159",
    seoDescription: "Child Development and Pedagogy master book for Central Teacher Eligibility Test.",
    fullDescription: "Complete Child Development & Pedagogy notes, Language 1 & 2 practice tests, Mathematics and Environmental Studies question banks for CTET Paper 1 and Paper 2 candidates.",
    tags: ["ctet", "teaching", "pedagogy", "child development"],
    averageRating: 4.6,
    reviewCount: 412,
    language: "English",
    pageCount: 230,
    fileSizeInMB: 19.1,
  },
];
