import { Book, Category } from "./books-store";

export const DEFAULT_CATEGORIES: Category[] = [
  { id: "cat-banking", name: "Banking Exams", seoslug: "banking-exams" },
  { id: "cat-upsc", name: "UPSC Civil Services", seoslug: "upsc" },
  { id: "cat-ssc", name: "SSC Exams", seoslug: "ssc" },
  { id: "cat-state-psc", name: "State PSC", seoslug: "state-psc" },
  { id: "cat-railways", name: "Railways Recruitment", seoslug: "railways" },
  { id: "cat-defense", name: "Defense Exams", seoslug: "defense" },
  { id: "cat-insurance", name: "Insurance Exams", seoslug: "insurance" },
  { id: "cat-teaching", name: "Teaching Exams", seoslug: "teaching" }
];

export const DEFAULT_BOOKS: Book[] = [
  {
    id: "upsc-prelims-csat",
    title: "UPSC Prelims CSAT Masterclass & 10 Years Solved Papers",
    seoslug: "upsc-prelims-csat",
    category: "UPSC Civil Services",
    publisher: "Exam Kart Press",
    pdfurl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    sampleurl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    listprice: "499",
    buyprice: "199",
    seoDescription: "Complete CSAT guide for UPSC Prelims with 10 years solved paper solutions, reading comprehension strategies, and quantitative shortcuts.",
    fullDescription: "Comprehensive preparation guide for UPSC Civil Services Examination Prelims GS Paper II (CSAT). Includes chapterwise solved questions from 2014 to 2024 with detailed step-by-step explanations.",
    tags: ["UPSC", "CSAT", "Prelims", "IAS", "Solved Papers"],
    averageRating: 4.8,
    reviewCount: 142,
    language: "English",
    pageCount: 380,
    fileSizeInMB: 12.4
  },
  {
    id: "ibps-sbi-po-solved-papers",
    title: "IBPS PO & SBI PO Prelims & Mains 15 Solved Mock Papers",
    seoslug: "ibps-sbi-po-solved-papers",
    category: "Banking Exams",
    publisher: "Exam Kart Press",
    pdfurl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    sampleurl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    listprice: "399",
    buyprice: "149",
    seoDescription: "15 full-length mock tests and previous year solved papers for IBPS PO, SBI PO, and RBI Grade B examinations.",
    fullDescription: "Master quantitative aptitude, high-level reasoning puzzles, and English language for IBPS PO and SBI PO exams with expert-curated practice papers and current financial awareness updates.",
    tags: ["IBPS PO", "SBI PO", "Banking", "Quantitative Aptitude", "Reasoning"],
    averageRating: 4.7,
    reviewCount: 98,
    language: "English",
    pageCount: 290,
    fileSizeInMB: 9.8
  },
  {
    id: "ssc-cgl-math-shortcuts",
    title: "SSC CGL Tier 1 & Tier 2 Mathematics Formulae & Shortcuts",
    seoslug: "ssc-cgl-math-shortcuts",
    category: "SSC Exams",
    publisher: "Exam Kart Press",
    pdfurl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    sampleurl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    listprice: "299",
    buyprice: "99",
    seoDescription: "Speed math formula book and short calculation tricks for SSC CGL, CHSL, and CPO examinations.",
    fullDescription: "Handpicked formula sheet and fast calculation tricks covering Algebra, Geometry, Trigonometry, Mensuration, and Data Interpretation for Staff Selection Commission exams.",
    tags: ["SSC CGL", "SSC CHSL", "Math", "Shortcuts", "Formula Book"],
    averageRating: 4.9,
    reviewCount: 215,
    language: "English",
    pageCount: 180,
    fileSizeInMB: 6.2
  },
  {
    id: "rrb-ntpc-general-science",
    title: "RRB NTPC & Group D General Science 2500+ Solved MCQs",
    seoslug: "rrb-ntpc-general-science",
    category: "Railways Recruitment",
    publisher: "Exam Kart Press",
    pdfurl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    sampleurl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    listprice: "349",
    buyprice: "129",
    seoDescription: "2500+ General Science MCQs with answer keys and topic summaries for Railway Recruitment Board exams.",
    fullDescription: "Targeted question bank for Physics, Chemistry, and Life Sciences designed strictly as per latest RRB CBT 1 and CBT 2 recruitment examination syllabus.",
    tags: ["RRB NTPC", "Railways", "General Science", "MCQs", "Group D"],
    averageRating: 4.6,
    reviewCount: 76,
    language: "English",
    pageCount: 240,
    fileSizeInMB: 8.5
  },
  {
    id: "nda-cds-solved-papers",
    title: "UPSC NDA & CDS Mathematics & General Knowledge Solved Papers",
    seoslug: "nda-cds-solved-papers",
    category: "Defense Exams",
    publisher: "Exam Kart Press",
    pdfurl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    sampleurl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    listprice: "449",
    buyprice: "179",
    seoDescription: "Previous 8 years solved papers and practice test modules for NDA, CDS, and AFCAT entrance exams.",
    fullDescription: "Complete defense exam prep guide featuring calculus & vector mathematics formula sheets, general knowledge summaries, and mock test series.",
    tags: ["NDA", "CDS", "Defense", "UPSC", "AFCAT"],
    averageRating: 4.8,
    reviewCount: 112,
    language: "English",
    pageCount: 320,
    fileSizeInMB: 11.1
  },
  {
    id: "state-psc-general-studies",
    title: "State PSC General Studies & Regional GK Solved Manual",
    seoslug: "state-psc-general-studies",
    category: "State PSC",
    publisher: "Exam Kart Press",
    pdfurl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    sampleurl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    listprice: "399",
    buyprice: "159",
    seoDescription: "State Public Service Commission general studies module and past prelims paper solutions.",
    fullDescription: "Designed for UPPSC, BPSC, MPPSC, RAS, and MPSC examinations. Covers static general studies, Indian polity, economic surveys, and state regional GK.",
    tags: ["State PSC", "UPPSC", "BPSC", "General Studies", "Prelims"],
    averageRating: 4.5,
    reviewCount: 64,
    language: "English",
    pageCount: 310,
    fileSizeInMB: 10.4
  },
  {
    id: "lic-aao-financial-awareness",
    title: "LIC AAO Financial & Insurance Market Awareness Practice Sets",
    seoslug: "lic-aao-financial-awareness",
    category: "Insurance Exams",
    publisher: "Exam Kart Press",
    pdfurl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    sampleurl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    listprice: "299",
    buyprice: "119",
    seoDescription: "Insurance market awareness notes, IRDAI guidelines digest, and mock tests for LIC AAO and NIACL exams.",
    fullDescription: "Master financial sector principles, insurance terms, IRDAI regulations, and quantitative reasoning for LIC Assistant Administrative Officer recruitment.",
    tags: ["LIC AAO", "Insurance", "Financial Awareness", "NIACL"],
    averageRating: 4.6,
    reviewCount: 43,
    language: "English",
    pageCount: 210,
    fileSizeInMB: 7.2
  },
  {
    id: "ctet-pedagogy-master-guide",
    title: "CTET Paper 1 & 2 Child Development & Pedagogy Master Guide",
    seoslug: "ctet-pedagogy-master-guide",
    category: "Teaching Exams",
    publisher: "Exam Kart Press",
    pdfurl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    sampleurl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    listprice: "349",
    buyprice: "139",
    seoDescription: "Child development and pedagogy notes, solved question banks, and mock test papers for CTET Paper 1 & 2.",
    fullDescription: "Complete pedagogical theories, learning psychology notes, language 1 & 2 practice sets, and previous year CTET question paper solutions with answer keys.",
    tags: ["CTET", "Pedagogy", "Teaching", "Paper 1", "Paper 2"],
    averageRating: 4.9,
    reviewCount: 156,
    language: "English",
    pageCount: 260,
    fileSizeInMB: 8.9
  }
];

